export const ContributeArrowNext = {
    background: '#FFFFFF',
    color: 'red',
    textAlign: 'center',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    cursor: 'pointer',
    boxShadow: '2px 2px 10px 0px #006F6221',
    zIndex: 10,
    width: '50px',
    height: '50px',
    padding: '10px',
    transform: 'translateY(8px)',
};
export const ContributeArrowPrev = {
    background: '#FFFFFF',
    borderRadius: '50%',
    boxShadow: '2px 2px 10px 0px #006F6221',
    cursor: 'pointer',
    width: '50px',
    height: '50px',
    textAlign: 'center',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
    padding: '10px',
    transform: 'translateY(8px)',
};
