export const StoreArrowNext = {
    background: '#FFFFFF',
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    right: '4%',
    color: 'red',
    width: '50px',
    height: '50px',
    textAlign: 'center',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    cursor: 'pointer',
    boxShadow: '2px 2px 10px 0px #006F6221',
    zIndex: 10,
};
export const StoreArrowPrev = {
    background: '#FFFFFF',
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    left: '4%',
    color: 'red',
    width: '50px',
    height: '50px',
    textAlign: 'center',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    cursor: 'pointer',
    boxShadow: '2px 2px 10px 0px #006F6221',
    zIndex: 10,
};
